version: "3"

networks:
  gitea-actions:
    name: gitea-actions
    external: true

services:
  gitea_act:
    image: gitea/act_runner:latest
    privileged: true
    restart: always
    environment:
      TZ: "Europe/Berlin"
      CONFIG_FILE: /data/config.yaml
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "<TOKEN>"
      GITEA_RUNNER_NAME: "runner"
    networks:
      - gitea-actions
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
      - ./data:/data:rw
