version: "3"

networks:
  postgres-network:
    name: postgres-network
    external: true
  traefik:
    name: traefik
    external: true

services:
  server:
    image: gitea/gitea:latest
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD={DB_PASS}
    restart: always
    networks:
      - postgres-network
      - traefik
    volumes:
      - ./data:/var/lib/gitea
      - ./data:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.domain.com`)"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22"
