version: "3"

networks:
  postgres-network:
    name: postgres-network
    external: true
  traefik:
    name: traefik
    external: true

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pg_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: { PASS_PG }
    networks:
      - postgres-network
      - traefik
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
